### ISSUE TITLE
Problems with manual stepping

### ISSUE THREAD

**Issue by briansemrau** [briansemrau/godot_box2d#57]
I'm foreseeing some potential issues with manual world stepping. Some of these problems I don't believe can be resolved cleanly.

---
**Application logic step**

All application logic dependent on physics step is currently inside `_physics_process`. However, this function is only called per Godot fixed time step. If a developer wants to handle per-step logic, they have to watch notifications in their script for `NOTIFICATION_WORLD_STEPPED`, which is gross IMO.

This could be resolved by creating a physics step callback like Godot's `_integrate_forces`. We could name it `_world_stepped`. This way we can also pass the time delta parameter `p_step`.

---
**Kinematic movement and animation player**

In Godot, it is not unusual for kinematic bodies to be controlled by AnimationPlayer. This is fine as long as physics calculation steps through time at the same rate as `_physics_process`. However, because we can't predict how much time the application will choose to step the world per fixed time step, kinematic motion will behave erratically.

Example of jittery kinematic motion with 2 physics steps / godot fixed step:
```
- step -      - position.X -
start         []
godot+world   -->[]      (vel.x = 3)
world         -->[]      (vel.x = 0)
godot+world   ----->[]   (vel.x = 3)
world         ----->[]   (vel.x = 0)
```
The above example is if we calculate the kinematic body's velocity from the change in transform _every world step_. Note that velocity is zero because the transform is updated in the fixed step. If we change it so that velocity is derived every _fixed step_, the body will jump ahead too far during the world step and be corrected on the fixed step. Because AnimationPlayer does not set velocity, this disaster can easily occur:

```
- step -      - position.X -
start         []
godot+world   -->[]       (vel.x =  3)
world         ----->[]    (vel.x =  3)
world         -------->[] (vel.x =  3)
godot+world   ----->[]    (vel.x = -3)
world         -->[]       (vel.x = -3)
world         []          (vel.x = -3)
godot_world   -------->[] (vel.x =  9)
```

There is no way to resolve this problem with manual stepping. This feature will be broken.

---
**Time scaling property**

If we keep the function for manual stepping, there should be clear documentation that it should only be used if you _know what you're doing_. However, a common use case of manual stepping may be to alter the flow of time. We can add a `time_scale` property to achieve this effect. With a known ratio between world step and fixed step time, kinematic motion jitter can be handled.

Time scaling could be implemented in two ways I can think of:
- Step using `(fixed step delta) * (time scale)`
- Implement game loop logic:
Accumulate `time_since_step` by `(fixed step delta) * (time scale)`. Step by `fixed step delta` while `time_since_step > fixed step delta`, `time_since_step -= fixed step delta`.

**Comment by jordo** [comment]
So my use case, in both my games right now now, isn't related to time_scaling (although that's an interesting use case as well).  

> **Application logic step**
> 
> All application logic dependent on physics step is currently inside `_physics_process`. However, this function is only called per Godot fixed time step. If a developer wants to handle per-step logic, they have to watch notifications in their script for `NOTIFICATION_WORLD_STEPPED`, which is gross IMO.
> 
> This could be resolved by creating a physics step callback like Godot's `_integrate_forces`. We could name it `_world_stepped`. This way we can also pass the time delta parameter `p_step`.

You shouldn't need any callback if you step the world manually.  The next line of code after you call step() is what gets executed right after the world is done simulating.  In the multithreaded scenario it doesn't make sense either because you just can't call back into the main thread randomly at any time after the world has completed a step().  The main thread may be in rendering code, or recording command buffers at time, or anywhere else really.  It basically always needs to be synced with a semaphore at the start of the next frame.  This is pretty much how the existing multi-threaded 2d physics works.  

From an application developer standpoint, I think if you choose to step your physics world manually (in whatever function or callback you choose. It could be `_physics_process`, but it could also be `_process` if you don't want a fixed step, or it could be anywhere else really, maybe one of your own application's threads) you have to be more aware of synchronization with your rendering.  You shouldn't need to depend on NOTIFICATION_WORLD_STEPPED to do this.  Once you take control of stepping the world yourself, you're really not constrained by anything with respect to application logic being dependent on `_physics_process`, you can step the world anywhere really.  Using the manual step, for example, I step the world in a game controller node in `_process` (which is guaranteed to run once per frame), and we use an accumulator to implement a fixed tick.  

With server-auth networked simulations it's really common for clients to 'set the b2world state back to a previous point in history' (server reconciliation), and then fast-forward back to real-time all in a single frame (many step() calls in a given frame to accomplish a fast-forward).  You have to have explicit control over stepping the world in order to accomplish this kind of thing correctly.  Often many times in a given frame a reset will happen, and step() will be called X times to catch the client back up to real-time.  The number of steps() then just depends on the latency between server and client.

I think this toggle is an advanced feature, you should know what you are doing to use it.   But it's also pretty useful for anyone who doesn't necessarily want to use a fixed physics step (avoiding any aliasing in single player games between _process dt and _physics_process dt).  

wrt animation player, ya I think if you want to manually step your physics world you will end up with a lot of irregularites with other godot systems that assume a fixed physics tick, and at a rate specified in the project settings.  I think this is probably just one edge case among potential others that would behave oddly.  I assume stuff like profiling and other stuff would be weird / broken as well.  

A time scaling property I think would be difficult to integrate properly into godot systems.  (how would that work with animation player, with perhaps multiple Box2DWorlds, etc).  I think just exposing the Step(float dt) adds some nice flexibility (can't really do rollback-resim networked physics without control over it).  But ya, I would consider it a 'know what you are doing' kind of thing.  But I think being able to use the physics system without necessarily bringing in other systems is a big win for flexibility.  Exposing the step with a manual dt basically allows you to use the world in whatever way you really want from an application developer's perspective, it's pretty powerful.

**Comment by briansemrau** [comment]
> You shouldn't need any callback if you step the world manually. The next line of code after you call step() is what gets executed right after the world is done simulating.

> From an application developer standpoint, I think if you choose to step your physics world manually (in whatever function or callback you choose. It could be _physics_process, but it could also be _process if you don't want a fixed step, or it could be anywhere else really, maybe one of your own application's threads) you have to be more aware of synchronization with your rendering. You shouldn't need to depend on NOTIFICATION_WORLD_STEPPED to do this.


The `_world_stepped` callback is a per-node virtual function like `_process` or `_physics_process` that the application developer can choose to implement if they need it. It is essentially the same as `_integrate_forces`.

The point is to provide a place for logic that always happens after every step. This allows the flexibility of calling `world.step(...)` anywhere you want without manually managing your general physics-step-dependent logic that must execute with/after it. For example, if a game were to implement dynamic physics effects like buoyancy, this is where that logic would go.

With regards to multithreading, yeah, we'd have to sync with the main thread and process the callbacks. Calls to `_integrate_forces` are added to a callback queue to be flushed before the next physics step.

Just for reference, this is the physics iteration loop in Godot from main.cpp (my comments, fluff removed):
```cpp
{ // physics iter
    PhysicsServer2D::get_singleton()->sync();
    PhysicsServer2D::get_singleton()->flush_queries(); // _integrate_forces callbacks

    OS::get_singleton()->get_main_loop()->physics_process(physics_step * time_scale));

    message_queue->flush(); // call_deferred handled I think

    PhysicsServer2D::get_singleton()->end_sync();
    PhysicsServer2D::get_singleton()->step(physics_step * time_scale);

    message_queue->flush();
}
```

**Comment by briansemrau** [comment]
And touching on my thoughts on time scaling, I've changed my mind and think it's best to leave implementation to the application. It's easy enough for the user to disable `auto_step` and add `world.step(delta * my_scale)` inside `_physics_process` (or wherever).

**Comment by jordo** [comment]
Ah ok, I see about `_world_stepped`.  that sounds great.  In the scenario of a separate physics thread, we may have to flush the message queue to get these callbacks to pump before the next physics_process.   `PhysicsServer2D::get_singleton()->sync();` is the semaphore that will block the main thread until the last frame's physics thread's step() is complete.  If it's similar to the `_integrate_forces callbacks` callback, then we probably want those callbacks on the main thread right after or before that `flush_queries()`

In the single threaded physics we would get the `_world_stepped` callbacks during the last line of your posted sample code.

**Comment by briansemrau** [comment]
I believe I've been able to resolve all the issues I brought up, so I'll close this assuming no further discussion is needed.
